#!/usr/bin/env python3
"""
Exports Google Sheets data to JSON files for the Bardi dashboard.
Reads: Job Summary Sheet + Membership Sheet
Writes: dashboard/data/jobs.json, dashboard/data/memberships.json, dashboard/data/config.json
"""

import os
import re
import json
from datetime import datetime, timedelta
from dotenv import load_dotenv
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

load_dotenv()

SHEET_ID            = os.environ["GOOGLE_SHEET_ID"]
MEMBERSHIP_SHEET_ID = os.environ["MEMBERSHIP_SHEET_ID"]
SA_JSON_PATH        = os.environ.get("GOOGLE_SA_JSON", "service_account.json")
SHEET_TAB           = os.environ.get("GOOGLE_SHEET_TAB", "Sheet1")
SCOPES              = ["https://www.googleapis.com/auth/spreadsheets.readonly"]

SUMMARY_TAB   = "Membership Summary"
CANCELLED_TAB = "Canceled & Expired Members"
CONFIG_TAB    = "Config"
DAYS_TO_KEEP  = 90

# The dashboard (dashboard/index.html) fetches its JSON from a path relative to
# itself, i.e. dashboard/data/. Write there so daily exports actually reach the
# live dashboard. (Root data/ was orphaned when the data folder was moved into
# dashboard/ — see commit "move data folder inside dashboard".)
OUTPUT_DIR = os.path.join("dashboard", "data")

EXCEL_EPOCH = datetime(1899, 12, 30)

PCT_FIELDS = {
    "Jobs Gross Margin %", "Payroll Adjustments as % of Sales",
    "Material Costs As % of Sales", "PO/Bill Costs As % of Sales",
    "Equip. Costs As % of Sales",
    "Materials + Equip. + PO/Bill Costs As % of Sales",
    "Total Cost As % of Sales", "Performance Pay as % of Sales",
    "Labor Pay as % of Sales", "Labor Burden as % of Sales",
}

# Canonical job column order, in the exact order run.py appends each job row.
# Kept in sync with run.py's SHEET_COLUMNS by hand (we can't import run.py here —
# it reads ServiceTitan env vars at import time that the export job doesn't set).
# Needed because the job data currently shares a tab whose first row is a 2-col
# Key/Value header, so we can't trust the sheet's own header row for job fields.
JOB_COLUMNS = [
    "Job #", "Invoice #", "Customer Name", "Invoice Date", "Job Type",
    "Business Unit", "Jobs Total", "Tax", "Jobs Payments",
    "Payroll Adjustments", "Payroll Adjustments as % of Sales",
    "Material Costs", "Material Costs As % of Sales",
    "PO/Bill Costs", "PO/Bill Costs As % of Sales",
    "Equipment Costs", "Equip. Costs As % of Sales", "Lead Generated By",
    "Materials + Equip. + PO/Bill Costs",
    "Materials + Equip. + PO/Bill Costs As % of Sales",
    "Jobs Total Costs", "Total Cost As % of Sales", "Labor",
    "Jobs Gross Margin", "Jobs Gross Margin %", "Jobs Subtotal", "Sold By",
    "Primary Technician", "Total Technician Paid Time", "Jobs Total Revenue",
    "Total Hours Worked", "Performance Pay", "Performance Pay as % of Sales",
    "Labor Pay", "Labor Pay as % of Sales", "Labor Burden",
    "Labor Burden as % of Sales", "Returns", "Total Labor Costs",
]


def is_job_row(row):
    """A job row is any row whose first cell is a numeric Job #.

    This lets us pull job rows out of a tab that also holds non-job rows
    (a stray Key/Value header, a monthly_budget config pair) without them
    hijacking the parse.
    """
    return bool(row) and str(row[0]).strip().isdigit()


def sheets_client():
    # In GitHub Actions, credentials are passed as JSON content via env var
    sa_content = os.environ.get("GOOGLE_SA_JSON_CONTENT")
    if sa_content:
        import tempfile
        info = json.loads(sa_content)
        creds = Credentials.from_service_account_info(info, scopes=SCOPES)
    else:
        creds = Credentials.from_service_account_file(SA_JSON_PATH, scopes=SCOPES)
    return build("sheets", "v4", credentials=creds)


def read_tab(svc, sheet_id, tab_name):
    try:
        result = svc.spreadsheets().values().get(
            spreadsheetId=sheet_id,
            range=f"'{tab_name}'"
        ).execute()
        return result.get("values", [])
    except Exception as e:
        print(f"  Could not read tab '{tab_name}': {e}")
        return []


def to_iso_date(val):
    """Normalize an Invoice Date cell to ISO YYYY-MM-DD.

    Google Sheets' values API returns *formatted* cell values, so a date can
    arrive as an Excel serial (46156), a US string (6/18/2026), or already ISO.
    The dashboard filters and buckets strictly on ISO YYYY-MM-DD, so anything
    else silently breaks the 90-day filter and daily-revenue chart.
    """
    if val is None:
        return ""
    s = str(val).strip()
    if not s:
        return ""

    # Excel serial number (e.g. 46156)
    try:
        n = int(float(s))
        if 40000 < n < 60000:
            return (EXCEL_EPOCH + timedelta(days=n)).strftime("%Y-%m-%d")
    except (ValueError, TypeError):
        pass

    # Already ISO YYYY-MM-DD (optionally with a time component)
    m = re.match(r"^(\d{4})-(\d{2})-(\d{2})", s)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"

    # US format M/D/YYYY or M/D/YY
    m = re.match(r"^(\d{1,2})/(\d{1,2})/(\d{2,4})$", s)
    if m:
        mo, day, yr = int(m.group(1)), int(m.group(2)), int(m.group(3))
        if yr < 100:
            yr += 2000
        return f"{yr:04d}-{mo:02d}-{day:02d}"

    return s


def fix_pct(val):
    """Convert raw 0-1 decimal to percentage string if needed."""
    if not val or val == '':
        return val
    if isinstance(val, str) and '%' in val:
        return val
    try:
        f = float(val)
        if -2 < f < 2:
            return f"{f * 100:.2f}%"
    except (ValueError, TypeError):
        pass
    return val


def rows_to_dicts(rows):
    if not rows or len(rows) < 2:
        return []
    headers = rows[0]
    result = []
    for row in rows[1:]:
        if not any(row):
            continue
        padded = row + [''] * (len(headers) - len(row))
        result.append(dict(zip(headers, padded)))
    return result


def clean_job_row(row):
    row["Invoice Date"] = to_iso_date(row.get("Invoice Date", ""))
    for field in PCT_FIELDS:
        if field in row:
            row[field] = fix_pct(row[field])
    return row


def export_jobs(svc):
    print(f"Reading job data from '{SHEET_TAB}'...")
    rows = read_tab(svc, SHEET_ID, SHEET_TAB)

    # Only rows whose first cell is a numeric Job # are jobs; everything else
    # (the tab's header row, stray config rows) is skipped. If the tab carries
    # its own proper job header ("Job #" in cell A1) we honor it, otherwise we
    # fall back to the canonical JOB_COLUMNS order run.py writes in.
    header = rows[0] if (rows and str(rows[0][0]).strip() == "Job #") else JOB_COLUMNS
    job_rows = [r for r in rows if is_job_row(r)]
    skipped  = len(rows) - len(job_rows)

    all_jobs = []
    for r in job_rows:
        padded = list(r) + [""] * (len(header) - len(r))
        all_jobs.append(clean_job_row(dict(zip(header, padded))))
    print(f"  {len(all_jobs)} job rows ({skipped} non-job rows skipped).")

    cutoff = (datetime.now() - timedelta(days=DAYS_TO_KEEP)).strftime("%Y-%m-%d")
    filtered = [r for r in all_jobs if r.get("Invoice Date", "") >= cutoff]
    print(f"  {len(filtered)} rows in last {DAYS_TO_KEEP} days.")

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    out_path = os.path.join(OUTPUT_DIR, "jobs.json")
    with open(out_path, "w") as f:
        json.dump({
            "exported_at": datetime.utcnow().isoformat() + "Z",
            "rows": filtered
        }, f, separators=(",", ":"))
    print(f"  Wrote {out_path}")


def export_memberships(svc):
    print("Reading membership data...")
    summary_rows   = read_tab(svc, MEMBERSHIP_SHEET_ID, SUMMARY_TAB)
    cancelled_rows = read_tab(svc, MEMBERSHIP_SHEET_ID, CANCELLED_TAB)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    out_path = os.path.join(OUTPUT_DIR, "memberships.json")
    with open(out_path, "w") as f:
        json.dump({
            "exported_at": datetime.utcnow().isoformat() + "Z",
            "summary":   rows_to_dicts(summary_rows),
            "cancelled": rows_to_dicts(cancelled_rows)
        }, f, separators=(",", ":"))
    print(f"  Wrote {out_path}")


def export_config(svc):
    print("Reading config...")
    config = {}
    rows = read_tab(svc, SHEET_ID, CONFIG_TAB)
    # The config tab currently also holds appended job rows (first cell = a
    # numeric Job #). Keep only real config: skip job rows and the Key/Value
    # header so config.json holds settings like monthly_budget, not job noise.
    for row in rows:
        if len(row) >= 2 and row[0] and not is_job_row(row) and row[0] != "Key":
            config[row[0]] = row[1]
    if not config:
        print("  No config keys found — writing empty config.")

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    out_path = os.path.join(OUTPUT_DIR, "config.json")
    with open(out_path, "w") as f:
        json.dump(config, f, separators=(",", ":"))
    print(f"  Wrote {out_path}")


def main():
    print("Connecting to Google Sheets...")
    svc = sheets_client()
    export_jobs(svc)
    export_memberships(svc)
    export_config(svc)
    print("Export complete.")


if __name__ == "__main__":
    main()
