#!/usr/bin/env python3
"""
ServiceTitan -> Google Sheets: Job Cost Data
Pulls completed jobs and appends one row per job to Google Sheets.

Usage:
    python run.py                          # yesterday's completed jobs
    python run.py --from 2026-01-01 --to 2026-01-31
"""

import os
import sys
import argparse
from datetime import datetime, timedelta

import time
import socket
import concurrent.futures
import requests
from dotenv import load_dotenv

socket.setdefaulttimeout(20)
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

load_dotenv()

# ── Config ──────────────────────────────────────────────────────────────────
ST_AUTH_URL      = "https://auth.servicetitan.io/connect/token"
ST_BASE_URL      = "https://api.servicetitan.io"
ST_TENANT_ID     = os.environ["ST_TENANT_ID"]
ST_CLIENT_ID     = os.environ["ST_CLIENT_ID"]
ST_CLIENT_SECRET = os.environ["ST_CLIENT_SECRET"]
ST_APP_KEY       = os.environ["ST_APP_KEY"]

SHEET_ID     = os.environ["GOOGLE_SHEET_ID"]
SHEET_TAB    = os.environ.get("GOOGLE_SHEET_TAB", "Sheet1")
SA_JSON_PATH = os.environ["GOOGLE_SA_JSON"]
SCOPES       = ["https://www.googleapis.com/auth/spreadsheets"]

# Must match your Google Sheet row 1 exactly, in order
SHEET_COLUMNS = [
    "Job #",
    "Invoice #",
    "Customer Name",
    "Invoice Date",
    "Job Type",
    "Business Unit",
    "Jobs Total",
    "Tax",
    "Jobs Payments",
    "Payroll Adjustments",
    "Payroll Adjustments as % of Sales",
    "Material Costs",
    "Material Costs As % of Sales",
    "PO/Bill Costs",
    "PO/Bill Costs As % of Sales",
    "Equipment Costs",
    "Equip. Costs As % of Sales",
    "Lead Generated By",
    "Materials + Equip. + PO/Bill Costs",
    "Materials + Equip. + PO/Bill Costs As % of Sales",
    "Jobs Total Costs",
    "Total Cost As % of Sales",
    "Labor",
    "Jobs Gross Margin",
    "Jobs Gross Margin %",
    "Jobs Subtotal",
    "Sold By",
    "Primary Technician",
    "Total Technician Paid Time",
    "Jobs Total Revenue",
    "Total Hours Worked",
    "Performance Pay",
    "Performance Pay as % of Sales",
    "Labor Pay",
    "Labor Pay as % of Sales",
    "Labor Burden",
    "Labor Burden as % of Sales",
    "Returns",
    "Total Labor Costs",
]


# ── Session + auth ───────────────────────────────────────────────────────────

SESSION = requests.Session()  # reuse TCP connections across all calls


def get_st_token() -> str:
    resp = SESSION.post(ST_AUTH_URL, data={
        "grant_type":    "client_credentials",
        "client_id":     ST_CLIENT_ID,
        "client_secret": ST_CLIENT_SECRET,
    }, timeout=30)
    if not resp.ok:
        raise SystemExit(f"Auth failed {resp.status_code}: {resp.text}")
    return resp.json()["access_token"]


def st_headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "ST-App-Key":    ST_APP_KEY,
        "Content-Type":  "application/json",
    }


# ── Paginated GET helper ─────────────────────────────────────────────────────

def st_get_all(token: str, path: str, params: dict = None, timeout: int = 20) -> list:
    url = f"{ST_BASE_URL}{path}"
    params = dict(params or {})
    params.setdefault("pageSize", 500)
    results = []
    page = 1
    while True:
        params["page"] = page
        for attempt in range(5):
            try:
                resp = SESSION.get(url, headers=st_headers(token), params=params, timeout=timeout)
                break
            except (requests.exceptions.Timeout,
                    requests.exceptions.ConnectionError):
                if attempt == 4:
                    print(f" [giving up on {path.split('/')[-1]}]", end="", flush=True)
                    return results
                wait = 2 ** attempt
                print(f" [retry {attempt+1} in {wait}s]", end="", flush=True)
                time.sleep(wait)
        if not resp.ok:
            return results
        data = resp.json()
        results.extend(data.get("data", []))
        if not data.get("hasMore", False):
            break
        page += 1
    return results


# ── Data fetchers ────────────────────────────────────────────────────────────

def get_completed_jobs(token: str, from_date: str, to_date: str) -> list:
    return st_get_all(token, f"/jpm/v2/tenant/{ST_TENANT_ID}/jobs", {
        "completedOnOrAfter":  f"{from_date}T00:00:00Z",
        "completedOnOrBefore": f"{to_date}T23:59:59Z",
        "jobStatus":           "Completed",
    })


def get_invoices(token: str, job_id: int) -> list:
    return st_get_all(token, f"/accounting/v2/tenant/{ST_TENANT_ID}/invoices", {
        "jobId": job_id,
    })


def get_po_costs(token: str, job_id: int) -> float:
    pos = st_get_all(token, f"/inventory/v2/tenant/{ST_TENANT_ID}/purchase-orders", {
        "jobId": job_id,
    })
    return sum(float(po.get("total", 0) or 0) for po in pos)


def get_campaign_names(token: str) -> dict:
    """Returns {campaign_id: campaign_name}."""
    campaigns = st_get_all(token, f"/crm/v2/tenant/{ST_TENANT_ID}/campaigns")
    return {c["id"]: c.get("name", "") for c in campaigns}


def get_technicians_by_job(token: str, from_date: str, to_date: str) -> dict:
    """Returns {job_id: technician_name} for the date range."""
    appts = st_get_all(token, f"/jpm/v2/tenant/{ST_TENANT_ID}/appointments", {
        "startsOnOrAfter":  f"{from_date}T00:00:00Z",
        "startsOnOrBefore": f"{to_date}T23:59:59Z",
    })
    result = {}
    for appt in appts:
        jid = appt.get("jobId")
        if not jid or jid in result:
            continue
        for t in (appt.get("technicians") or []):
            if t.get("isPrimary") or t.get("isPrimaryTechnician") or jid not in result:
                result[jid] = (t.get("technician") or {}).get("name", "") or t.get("name", "")
    return result


EMPTY_PAY = {
    "labor_pay": 0.0, "performance_pay": 0.0, "payroll_adjustments": 0.0,
    "labor_burden": 0.0, "paid_hours": 0.0, "worked_hours": 0.0,
}


def _fetch_payroll_inner(token: str, job_id: int) -> dict:
    """Runs in a worker thread so we can enforce a hard wall-clock timeout."""
    result = dict(EMPTY_PAY)
    session = requests.Session()
    hdrs = st_headers(token)

    resp = session.get(
        f"{ST_BASE_URL}/payroll/v2/tenant/{ST_TENANT_ID}/gross-pay-items",
        headers=hdrs, params={"jobId": job_id, "pageSize": 500}, timeout=10,
    )
    if resp.ok:
        for item in resp.json().get("data", []):
            itype  = (item.get("grossPayItemType") or "").lower()
            amount = float(item.get("amount") or 0)
            hours  = float(item.get("paidDurationHours") or 0)
            if "performance" in itype or "spiff" in itype or "bonus" in itype:
                result["performance_pay"] += amount
            else:
                result["labor_pay"]  += amount
                result["paid_hours"] += hours
            result["worked_hours"] += hours

    resp2 = session.get(
        f"{ST_BASE_URL}/payroll/v2/tenant/{ST_TENANT_ID}/payroll-adjustments",
        headers=hdrs, params={"jobId": job_id, "pageSize": 500}, timeout=10,
    )
    if resp2.ok:
        for adj in resp2.json().get("data", []):
            if adj.get("active", True):
                result["payroll_adjustments"] += float(adj.get("amount") or 0)

    return result


def get_payroll(token: str, job_id: int) -> dict:
    """Fetch payroll with a hard 12-second wall-clock timeout via thread."""
    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
        future = ex.submit(_fetch_payroll_inner, token, job_id)
        try:
            return future.result(timeout=12)
        except Exception:
            return dict(EMPTY_PAY)


# ── Invoice parsing ──────────────────────────────────────────────────────────

def parse_invoices(invoices: list) -> dict:
    """Aggregate invoice fields across all invoices for a job."""
    out = {
        "invoice_number": "",
        "invoice_date":   "",
        "customer_name":  "",
        "business_unit":  "",
        "job_type":       "",
        "subtotal":       0.0,
        "tax":            0.0,
        "total":          0.0,
        "payments":       0.0,
        "returns":        0.0,
        "material_cost":  0.0,
        "equipment_cost": 0.0,
    }
    if not invoices:
        return out

    # Use the most recent invoice for header fields
    primary = sorted(invoices, key=lambda x: x.get("invoiceDate") or "", reverse=True)[0]
    out["invoice_number"] = primary.get("referenceNumber", "") or primary.get("id", "")
    out["invoice_date"]   = (primary.get("invoiceDate") or "")[:10]
    out["customer_name"]  = (primary.get("customer") or {}).get("name", "")
    out["business_unit"]  = (primary.get("businessUnit") or {}).get("name", "")
    out["job_type"]       = (primary.get("job") or {}).get("type", "")

    for invoice in invoices:
        out["subtotal"] += float(invoice.get("subTotal",  0) or 0)
        out["tax"]      += float(invoice.get("salesTax",  0) or 0)
        out["total"]    += float(invoice.get("total",     0) or 0)

        # payments = what has been paid = total - remaining balance
        total   = float(invoice.get("total",   0) or 0)
        balance = float(invoice.get("balance", 0) or 0)
        out["payments"] += max(total - balance, 0)

        # Line items — split by type
        for item in (invoice.get("items") or []):
            item_type = (item.get("skuType") or item.get("type") or "").lower()
            cost      = float(item.get("cost", 0) or 0)
            qty       = float(item.get("quantity", 1) or 1)
            line_cost = cost * qty

            if item_type == "material":
                out["material_cost"]  += line_cost
            elif item_type == "equipment":
                out["equipment_cost"] += line_cost
            elif item_type in ("return", "returns"):
                out["returns"] += abs(float(item.get("price", 0) or 0)) * qty

    return out


# ── Computed fields ──────────────────────────────────────────────────────────

def pct(numerator: float, denominator: float) -> str:
    if not denominator:
        return ""
    return f"{(numerator / denominator * 100):.2f}%"


def fmt(value: float) -> str:
    return f"{value:.2f}"


def build_row(job: dict, inv: dict, po_cost: float, pay: dict,
              campaigns: dict, tech_by_job: dict) -> list:
    revenue = inv["total"]

    material_cost  = inv["material_cost"]
    equipment_cost = inv["equipment_cost"]
    po_bill_cost   = po_cost

    labor_pay           = pay["labor_pay"]
    performance_pay     = pay["performance_pay"]
    payroll_adjustments = pay["payroll_adjustments"]
    labor_burden        = pay["labor_burden"]
    paid_hours          = pay["paid_hours"]
    worked_hours        = pay["worked_hours"]

    labor             = labor_pay + performance_pay + payroll_adjustments
    total_labor_costs = labor + labor_burden
    mat_equip_po      = material_cost + equipment_cost + po_bill_cost
    total_costs       = total_labor_costs + mat_equip_po
    gross_margin      = revenue - total_costs

    job_id       = job.get("id")
    campaign_id  = job.get("campaignId")
    lead_source  = campaigns.get(campaign_id, "") if campaign_id else ""
    primary_tech = tech_by_job.get(job_id, "")

    row_data = {
        "Job #":                                          job.get("jobNumber", ""),
        "Invoice #":                                      inv["invoice_number"],
        "Customer Name":                                  inv["customer_name"],
        "Invoice Date":                                   inv["invoice_date"],
        "Job Type":                                       inv["job_type"],
        "Business Unit":                                  inv["business_unit"],
        "Jobs Total":                                     fmt(inv["total"]),
        "Tax":                                            fmt(inv["tax"]),
        "Jobs Payments":                                  fmt(inv["payments"]),
        "Payroll Adjustments":                            fmt(payroll_adjustments),
        "Payroll Adjustments as % of Sales":              pct(payroll_adjustments, revenue),
        "Material Costs":                                 fmt(material_cost),
        "Material Costs As % of Sales":                   pct(material_cost, revenue),
        "PO/Bill Costs":                                  fmt(po_bill_cost),
        "PO/Bill Costs As % of Sales":                    pct(po_bill_cost, revenue),
        "Equipment Costs":                                fmt(equipment_cost),
        "Equip. Costs As % of Sales":                     pct(equipment_cost, revenue),
        "Lead Generated By":                              lead_source,
        "Materials + Equip. + PO/Bill Costs":             fmt(mat_equip_po),
        "Materials + Equip. + PO/Bill Costs As % of Sales": pct(mat_equip_po, revenue),
        "Jobs Total Costs":                               fmt(total_costs),
        "Total Cost As % of Sales":                       pct(total_costs, revenue),
        "Labor":                                          fmt(labor),
        "Jobs Gross Margin":                              fmt(gross_margin),
        "Jobs Gross Margin %":                            pct(gross_margin, revenue),
        "Jobs Subtotal":                                  fmt(inv["subtotal"]),
        "Sold By":                                        "",  # soldById needs employee lookup
        "Primary Technician":                             primary_tech,
        "Total Technician Paid Time":                     fmt(paid_hours),
        "Jobs Total Revenue":                             fmt(revenue),
        "Total Hours Worked":                             fmt(worked_hours),
        "Performance Pay":                                fmt(performance_pay),
        "Performance Pay as % of Sales":                  pct(performance_pay, revenue),
        "Labor Pay":                                      fmt(labor_pay),
        "Labor Pay as % of Sales":                        pct(labor_pay, revenue),
        "Labor Burden":                                   fmt(labor_burden),
        "Labor Burden as % of Sales":                     pct(labor_burden, revenue),
        "Returns":                                        fmt(inv["returns"]),
        "Total Labor Costs":                              fmt(total_labor_costs),
    }

    return [row_data.get(col, "") for col in SHEET_COLUMNS]


# ── Google Sheets ────────────────────────────────────────────────────────────

def sheets_client():
    creds = Credentials.from_service_account_file(SA_JSON_PATH, scopes=SCOPES)
    svc   = build("sheets", "v4", credentials=creds)
    meta  = svc.spreadsheets().get(spreadsheetId=SHEET_ID).execute()
    tab   = SHEET_TAB if SHEET_TAB != "Sheet1" else meta["sheets"][0]["properties"]["title"]
    return svc, tab


def get_existing_job_numbers(svc, tab: str) -> set:
    result = svc.spreadsheets().values().get(
        spreadsheetId=SHEET_ID,
        range=f"'{tab}'!A:A",
    ).execute()
    rows = result.get("values", [])
    return {r[0] for r in rows[1:] if r}  # skip header row


def append_rows(svc, tab: str, rows: list[list]) -> int:
    result = svc.spreadsheets().values().append(
        spreadsheetId=SHEET_ID,
        range=f"'{tab}'!A1",
        valueInputOption="USER_ENTERED",
        insertDataOption="INSERT_ROWS",
        body={"values": rows},
    ).execute()
    return result.get("updates", {}).get("updatedRows", 0)


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    yesterday = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
    today     = datetime.now().strftime("%Y-%m-%d")

    parser = argparse.ArgumentParser()
    parser.add_argument("--from", dest="from_date", default=yesterday, metavar="YYYY-MM-DD")
    parser.add_argument("--to",   dest="to_date",   default=today,     metavar="YYYY-MM-DD")
    args = parser.parse_args()

    print(f"Date range: {args.from_date} to {args.to_date}")

    print("Authenticating to ServiceTitan...")
    token = get_st_token()

    print("Connecting to Google Sheet...")
    svc, tab = sheets_client()
    existing = get_existing_job_numbers(svc, tab)
    print(f"  {len(existing)} existing job(s) in sheet.")

    print("Fetching completed jobs...")
    jobs = get_completed_jobs(token, args.from_date, args.to_date)
    print(f"  {len(jobs)} job(s) found.")

    jobs = [j for j in jobs if str(j.get("jobNumber", "")) not in existing]
    print(f"  {len(jobs)} new job(s) after deduplication.")

    if not jobs:
        print("Nothing new to write.")
        sys.exit(0)

    print("Fetching campaigns...")
    campaigns = get_campaign_names(token)
    print(f"  {len(campaigns)} campaigns loaded.")

    print("Fetching technician assignments...")
    tech_by_job = get_technicians_by_job(token, args.from_date, args.to_date)
    print(f"  {len(tech_by_job)} job(s) have technician data.")

    output_rows = []
    for i, job in enumerate(jobs, 1):
        job_id  = job["id"]
        job_num = job.get("jobNumber", job_id)
        print(f"  [{i}/{len(jobs)}] Job {job_num}", end="", flush=True)

        print(" invoices...", end="", flush=True)
        invoices = get_invoices(token, job_id)
        inv_data = parse_invoices(invoices)

        print(" POs...", end="", flush=True)
        po_cost = get_po_costs(token, job_id)

        print(" payroll...", end="", flush=True)
        pay = get_payroll(token, job_id)

        output_rows.append(build_row(job, inv_data, po_cost, pay, campaigns, tech_by_job))
        print(" done")
        time.sleep(0.1)

    print(f"Writing {len(output_rows)} row(s) to Google Sheet...")
    written = append_rows(svc, tab, output_rows)
    print(f"Done. {written} row(s) written.")


if __name__ == "__main__":
    main()
