#!/usr/bin/env python3
"""
One-time setup: writes the header row to your Google Sheet.
Run this once before using run.py.

Usage:
    python setup_sheet.py
"""

import os
from dotenv import load_dotenv
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

load_dotenv()

SHEET_ID     = os.environ["GOOGLE_SHEET_ID"]
SHEET_TAB    = os.environ.get("GOOGLE_SHEET_TAB", "Sheet1")
SA_JSON_PATH = os.environ["GOOGLE_SA_JSON"]
SCOPES       = ["https://www.googleapis.com/auth/spreadsheets"]

HEADERS = [
    "Job #",
    "Invoice #",
    "Customer Name",
    "Invoice Date",
    "Job Type",
    "Business Unit",
    "Jobs Total",
    "Tax",
    "Jobs Payments",
    "Payroll Adjustments",
    "Payroll Adjustments as % of Sales",
    "Material Costs",
    "Material Costs As % of Sales",
    "PO/Bill Costs",
    "PO/Bill Costs As % of Sales",
    "Equipment Costs",
    "Equip. Costs As % of Sales",
    "Lead Generated By",
    "Materials + Equip. + PO/Bill Costs",
    "Materials + Equip. + PO/Bill Costs As % of Sales",
    "Jobs Total Costs",
    "Total Cost As % of Sales",
    "Labor",
    "Jobs Gross Margin",
    "Jobs Gross Margin %",
    "Jobs Subtotal",
    "Sold By",
    "Primary Technician",
    "Total Technician Paid Time",
    "Jobs Total Revenue",
    "Total Hours Worked",
    "Performance Pay",
    "Performance Pay as % of Sales",
    "Labor Pay",
    "Labor Pay as % of Sales",
    "Labor Burden",
    "Labor Burden as % of Sales",
    "Returns",
    "Total Labor Costs",
]

def main():
    print("Connecting to Google Sheets...")
    creds = Credentials.from_service_account_file(SA_JSON_PATH, scopes=SCOPES)
    svc   = build("sheets", "v4", credentials=creds)
    sheet = svc.spreadsheets()

    # Check if row 1 already has data
    existing = sheet.values().get(
        spreadsheetId=SHEET_ID,
        range=f"{SHEET_TAB}!1:1"
    ).execute()

    if existing.get("values"):
        print("⚠️  Row 1 already has data:")
        print(f"   {existing['values'][0][:5]}...")
        confirm = input("Overwrite with correct headers? (yes/no): ").strip().lower()
        if confirm != "yes":
            print("Aborted. No changes made.")
            return

    # Write headers to row 1
    sheet.values().update(
        spreadsheetId=SHEET_ID,
        range=f"{SHEET_TAB}!A1",
        valueInputOption="RAW",
        body={"values": [HEADERS]}
    ).execute()

    print(f"✅ Done. {len(HEADERS)} headers written to row 1 of '{SHEET_TAB}'.")
    print("Your sheet is ready. Run `python run.py` to start pulling data.")

if __name__ == "__main__":
    main()
